name: TWRPTreeGeneratorAction

on:
  workflow_dispatch:
	inputs:
	  rom_url:
		description: 'ROM 下载直链'
		required: true
		default: 'https://mirrorbits.lineageos.org/full/tissot/20230425/lineage-19.1-20230425-nightly-tissot-signed.zip'

jobs:
  TWRPTreeGeneratorAction:
	runs-on: ubuntu-latest
	steps:
	  - name: Check out 
		uses: actions/checkout@v2

	  - name: Install dependences
		run: |
		  sudo apt-get update
		  sudo apt-get -y install python3-pip p7zip-full
		  sudo apt install aria2 liblzma-dev brotli lz4
		  pip3 install backports.lzma pycrypto
		  pip install protobuf==3.20
		  BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
		  echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

	  - name: Generate Device Tree 
		run: |
		  cd ~
		  git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
		  cd Firmware_extractor
		  aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
		  ./extractor.sh firmware.zip
		  cd ${{ github.workspace }}
		  touch info.md
		  echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
		  echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> info.md
		  mv ~/Firmware_extractor/out/init_boot.img ~/Firmware_extractor/out/boot.img
		  pip3 install twrpdtgen
		  python3 -m twrpdtgen ~/Firmware_extractor/out/boot.img
		  cd ~
		  7z a -r -t7z ~/output GeneratedTWRPDeviceTree.7z

	  - name: Upload Device Tree
		uses: ncipollo/release-action@v1.12.0
		with:
			artifacts: "~/GeneratedTWRPDeviceTree.7z"
			bodyfile: "${{ github.workspace }}/info.md"
			tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
			token: ${{ secrets.GITHUB_TOKEN }}
